[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
no_implicit_optional = true
strict = false
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["infra.sqlite_repo"]
disable_error_code = ["call-arg"]

[tool.ruff]
target-version = "py311"
line-length = 160

[tool.ruff.lint]
select = ["F","E","I","B"]  
ignore = []                 

[tool.ruff.lint.per-file-ignores]
"api/main.py" = ["B008"]
"tests/*" = ["E501","B007","B017"]
