name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || true

      - name: Lint with Ruff (autofix first, luego verifica)
        run: |
          pip install ruff
          ruff check . --fix
          ruff check . --exit-non-zero-on-fix

      - name: Type-check with MyPy
        run: mypy . --python-version=3.11

      - name: Run tests with pytest + coverage
        run: |
          pip install pytest pytest-cov
          export TEST_TMP_DIR=$(mktemp -d)
          pytest --cov=. --cov-report=xml --cov-fail-under=80 --cov-report=term-missing

