name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy ruff numpy

      - name: Ruff
        run: ruff check .

      - name: Mypy
        run: mypy . --python-version=3.11

