name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt || true

    - name: Lint with Ruff
      run: ruff check .

    - name: Type-check with MyPy
      run: mypy . --python-version=3.11

    - name: Run tests with pytest + coverage
      run: |
        pip install pytest pytest-cov
        pytest --cov=. --cov-report=xml --cov-report=term-missing

